version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - cmake
    - ninja-build
  jobs:
    pre_build:
      - mkdir build
      - cmake -B build -DBUILD_DOCS=ON -DNIC_TYPE=AF_XDP
      - ninja -C build Sphinx
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp -r build/docs/sphinx/html $READTHEDOCS_OUTPUT/html/ 
    
python:
  install:
    - requirements: docs/requirements.txt
