name: Build static

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile.build_static
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=local,dest=outputs
        build-args: |
          DPDK_PLATFORM=generic

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: ${{ github.workspace }}/outputs/*

